# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sledge-MobileGate
version:      0.15
version_from: lib/Sledge/MobileGate.pm
installdirs:  site
requires:
    HTML::Entities::ImodePictogram: 0
    HTTP::MobileAgent:             0
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
